resilience4j.circuitbreaker:
  configs:
    default:
        registerHealthIndicator: true
        eventConsumerBufferSize: 10
        automaticTransitionFromOpenToHalfOpenEnabled: true
        failureRateThreshold: 50                  # failure rate threshold in percentage
        minimumNumberOfCalls: 5                   # minimum calls before the CircuitBreaker can calculate the error rate.
        permittedNumberOfCallsInHalfOpenState: 3  # number of permitted calls when the CircuitBreaker is half open
        slidingWindowSize: 9                     # start rate calc after 10 calls
        waitDurationInOpenState: 5s               # time that the CircuitBreaker should wait before transitioning from open to half-open
        slidingWindowType: COUNT_BASED
        recordExceptions:                          # increment error rate if following exception occurs
  instances:
    backend_test:
      baseConfig: default

resilience4j.timelimiter:
  configs:
    default:
      cancelRunningFuture: false
      timeoutDuration: 2s
  instances:
    backend_test:
      baseConfig: default


resilience4j.retry:
  configs:
    default:
      maxAttempts: 3
      waitDuration: 10
  instances:
    backend_test:
      baseConfig: default

management:
  health:
    circuitbreakers:
      enabled: true
  endpoints:
    web:
      exposure:
#        include: health
        include: '*'
  endpoint:
    health:
      show-details: always

test:
  test: hellowWorld
